#############################################################################
# Makefile for building: Inventory.app/Contents/MacOS/Inventory
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  Inventory.pro
# Template: app
# Command: /Users/jeffreychen/Qt/5.4/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile Inventory.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../Qt/5.4/clang_64/mkspecs/macx-clang -I. -I../../../Qt/5.4/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers -I../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -F/Users/jeffreychen/Qt/5.4/clang_64/lib
QMAKE         = /Users/jeffreychen/Qt/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Inventory1.0.0
DISTDIR = /Users/jeffreychen/Projects/Qt/Inventory/.tmp/Inventory1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/jeffreychen/Qt/5.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/jeffreychen/Qt/5.4/clang_64/lib -framework QtPrintSupport -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		dialog.cpp \
		Vegetable.cpp \
		Inventory.cpp \
		History.cpp \
		Remaining.cpp \
		Return.cpp \
		returnto.cpp \
		translator.cpp \
		imenubar.cpp moc_dialog.cpp \
		moc_imenubar.cpp
OBJECTS       = main.o \
		dialog.o \
		Vegetable.o \
		Inventory.o \
		History.o \
		Remaining.o \
		Return.o \
		returnto.o \
		translator.o \
		imenubar.o \
		moc_dialog.o \
		moc_imenubar.o
DIST          = ../../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		Inventory.pro dialog.h \
		Vegetable.h \
		Inventory.h \
		History.h \
		Remaining.h \
		Return.h \
		returnto.h \
		IConst.h \
		translator.h \
		imenubar.h main.cpp \
		dialog.cpp \
		Vegetable.cpp \
		Inventory.cpp \
		History.cpp \
		Remaining.cpp \
		Return.cpp \
		returnto.cpp \
		translator.cpp \
		imenubar.cpp
QMAKE_TARGET  = Inventory
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Inventory.app/Contents/MacOS/Inventory

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_dialog.h ui_returns.h $(OBJECTS)  
	@test -d Inventory.app/Contents/MacOS/ || mkdir -p Inventory.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Inventory.pro ../../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		Inventory.pro \
		/Users/jeffreychen/Qt/5.4/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl \
		/Users/jeffreychen/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/jeffreychen/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/jeffreychen/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile Inventory.pro
../../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.4/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.4/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf:
../../../Qt/5.4/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.4/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.4/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.4/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.4/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf:
../../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.4/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.4/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.4/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.4/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.4/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.4/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.4/clang_64/mkspecs/features/lex.prf:
Inventory.pro:
/Users/jeffreychen/Qt/5.4/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl:
/Users/jeffreychen/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/jeffreychen/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/jeffreychen/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile Inventory.pro

qmake_all: FORCE

Inventory.app/Contents/PkgInfo: 
	@test -d Inventory.app/Contents || mkdir -p Inventory.app/Contents
	@$(DEL_FILE) Inventory.app/Contents/PkgInfo
	@echo "APPL????" >Inventory.app/Contents/PkgInfo
Inventory.app/Contents/Resources/empty.lproj: 
	@test -d Inventory.app/Contents/Resources || mkdir -p Inventory.app/Contents/Resources
	@touch Inventory.app/Contents/Resources/empty.lproj
	
Inventory.app/Contents/Info.plist: 
	@test -d Inventory.app/Contents || mkdir -p Inventory.app/Contents
	@$(DEL_FILE) Inventory.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.Inventory,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Inventory,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.4/clang_64/mkspecs/macx-clang/Info.plist.app >Inventory.app/Contents/Info.plist

all: Makefile \
		Inventory.app/Contents/PkgInfo \
		Inventory.app/Contents/Resources/empty.lproj \
		Inventory.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents dialog.h Vegetable.h Inventory.h History.h Remaining.h Return.h returnto.h IConst.h translator.h imenubar.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp dialog.cpp Vegetable.cpp Inventory.cpp History.cpp Remaining.cpp Return.cpp returnto.cpp translator.cpp imenubar.cpp $(DISTDIR)/
	$(COPY_FILE) --parents dialog.ui returns.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Inventory.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_dialog.cpp moc_imenubar.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp moc_imenubar.cpp
moc_dialog.cpp: ../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		Inventory.h \
		returnto.h \
		Return.h \
		History.h \
		Remaining.h \
		Vegetable.h \
		translator.h \
		IConst.h \
		imenubar.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListWidgetItem \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../../Qt/5.4/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QPrinter \
		../../../Qt/5.4/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprinter.h \
		dialog.h
	/Users/jeffreychen/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/jeffreychen/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/jeffreychen/Projects/Qt/Inventory -I/Users/jeffreychen/Qt/5.4/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/jeffreychen/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/jeffreychen/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/jeffreychen/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/jeffreychen/Qt/5.4/clang_64/lib dialog.h -o moc_dialog.cpp

moc_imenubar.cpp: ../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		translator.h \
		IConst.h \
		imenubar.h
	/Users/jeffreychen/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/jeffreychen/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/jeffreychen/Projects/Qt/Inventory -I/Users/jeffreychen/Qt/5.4/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/jeffreychen/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/jeffreychen/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/jeffreychen/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/jeffreychen/Qt/5.4/clang_64/lib imenubar.h -o moc_imenubar.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_dialog.h ui_returns.h
compiler_uic_clean:
	-$(DEL_FILE) ui_dialog.h ui_returns.h
ui_dialog.h: dialog.ui
	/Users/jeffreychen/Qt/5.4/clang_64/bin/uic dialog.ui -o ui_dialog.h

ui_returns.h: returns.ui
	/Users/jeffreychen/Qt/5.4/clang_64/bin/uic returns.ui -o ui_returns.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp dialog.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		Inventory.h \
		returnto.h \
		Return.h \
		History.h \
		Remaining.h \
		Vegetable.h \
		translator.h \
		IConst.h \
		imenubar.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListWidgetItem \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../../Qt/5.4/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QPrinter \
		../../../Qt/5.4/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprinter.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

dialog.o: dialog.cpp dialog.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		Inventory.h \
		returnto.h \
		Return.h \
		History.h \
		Remaining.h \
		Vegetable.h \
		translator.h \
		IConst.h \
		imenubar.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListWidgetItem \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../../Qt/5.4/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QPrinter \
		../../../Qt/5.4/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprinter.h \
		ui_dialog.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/Qtcore \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qabstractanimation.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qanimationgroup.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qparallelanimationgroup.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpauseanimation.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpropertyanimation.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsequentialanimationgroup.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qvariantanimation.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextcodec.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcompilerdetection.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qendian.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qflags.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobal.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qglobalstatic.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qisenum.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlibraryinfo.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qnamespace.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qnumeric.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qprocessordetection.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsysinfo.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsystemdetection.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtypeinfo.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtypetraits.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbuffer.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatastream.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdir.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdiriterator.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfiledevice.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileselector.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfilesystemwatcher.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qiodevice.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlockfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qloggingcategory.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qprocess.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qresource.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsavefile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstandardpaths.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstorageinfo.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtemporarydir.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtemporaryfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qurl.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qurlquery.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qabstractitemmodel.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qabstractproxymodel.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qidentityproxymodel.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qitemselectionmodel.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsortfilterproxymodel.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlistmodel.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qjsonarray.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qjsondocument.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qjsonobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qjsonvalue.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qabstracteventdispatcher.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qabstractnativeeventfilter.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbasictimer.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcoreapplication.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcoreevent.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qeventloop.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmath.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmetaobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmetatype.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmimedata.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobjectcleanuphandler.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobjectdefs.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpointer.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedmemory.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsignalmapper.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsocketnotifier.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsystemsemaphore.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtranslator.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qvariant.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qwineventnotifier.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmimedatabase.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmimetype.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfactoryinterface.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlibrary.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qplugin.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpluginloader.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/quuid.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qabstractstate.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qabstracttransition.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qeventtransition.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfinalstate.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qhistorystate.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsignaltransition.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstate.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstatemachine.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qatomic.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qexception.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfuture.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfutureinterface.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfuturesynchronizer.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfuturewatcher.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qgenericatomic.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmutex.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qreadwritelock.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qresultstore.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qrunnable.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsemaphore.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qthreadpool.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qthreadstorage.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qwaitcondition.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qalgorithms.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qarraydata.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qarraydataops.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qarraydatapointer.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbitarray.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearraylist.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearraymatcher.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qchar.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcollator.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcommandlineoption.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcommandlineparser.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcontainerfwd.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcontiguouscache.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcryptographichash.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qeasingcurve.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qelapsedtimer.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qhash.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qiterator.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qline.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlinkedlist.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlocale.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmap.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmargins.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmessageauthenticationcode.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpair.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qpoint.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qqueue.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qrect.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qrefcount.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qregexp.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qregularexpression.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qscopedpointer.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qscopedvaluerollback.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qset.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qshareddata.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsize.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstack.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringbuilder.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringmatcher.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextboundaryfinder.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimeline.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimezone.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qvarlengtharray.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qxmlstream.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtcoreversion.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QtGui \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessible.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessiblebridge.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessibleobject.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessibleplugin.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qbitmap.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qicon.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qiconengine.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qiconengineplugin.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qimageiohandler.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagereader.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagewriter.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qmovie.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qpicture.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qpictureformatplugin.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmap.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmapcache.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qstandarditemmodel.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qclipboard.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcursor.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qdrag.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericplugin.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericpluginfactory.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qguiapplication.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qinputmethod.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qkeysequence.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qoffscreensurface.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglcontext.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglwindow.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qpaintdevicewindow.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qpalette.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixelformat.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qrasterwindow.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qscreen.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qsessionmanager.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qstylehints.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qsurface.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qsurfaceformat.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qtouchdevice.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qwindow.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qwindowdefs.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericmatrix.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qmatrix4x4.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qquaternion.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector2d.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector3d.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector4d.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengl.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglbuffer.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengldebug.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglframebufferobject.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglfunctions.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglpaintdevice.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglpixeltransferoptions.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglshaderprogram.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengltexture.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengltimerquery.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglversionfunctions.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglvertexarrayobject.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qbackingstore.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qbrush.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qmatrix.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagedpaintdevice.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagelayout.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagesize.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qpaintdevice.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qpaintengine.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainterpath.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qpdfwriter.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qpen.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qpolygon.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qregion.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qrgb.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qtransform.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qabstracttextdocumentlayout.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qfont.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontdatabase.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontinfo.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontmetrics.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qglyphrun.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qrawfont.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qstatictext.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextcursor.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocument.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocumentfragment.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocumentwriter.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextformat.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextlayout.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextlist.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextobject.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextoption.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qtexttable.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qdesktopservices.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qvalidator.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qtguiversion.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QInputDialog \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qinputdialog.h \
		../../../Qt/5.4/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QPrintPreviewWidget \
		../../../Qt/5.4/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintpreviewwidget.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QtWidgets \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/complexwidgets.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/itemviews.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblemenu.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblewidget.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblewidgets.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/rangecontrols.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/simplewidgets.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolordialog.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qerrormessage.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfilesystemmodel.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontdialog.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressdialog.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwizard.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicseffect.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsanchorlayout.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsgridlayout.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitem.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitemanimation.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayout.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayoutitem.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslinearlayout.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsproxywidget.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicssceneevent.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicstransform.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgraphicswidget.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemdelegate.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemview.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolumnview.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatawidgetmapper.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdirmodel.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfileiconprovider.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qheaderview.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemdelegate.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemeditorfactory.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistview.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleditemdelegate.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtableview.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreeview.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidgetitemiterator.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qactiongroup.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qformlayout.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesture.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgesturerecognizer.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayout.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlayoutitem.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qopenglwidget.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qshortcut.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizepolicy.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedlayout.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtooltip.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwhatsthis.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidgetaction.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeyeventtransition.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmouseeventtransition.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommonstyle.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdrawutil.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qproxystyle.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyle.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylefactory.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleoption.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstylepainter.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstyleplugin.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolormap.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcompleter.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscroller.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollerproperties.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsystemtrayicon.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundogroup.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundostack.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qundoview.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractbutton.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractslider.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractspinbox.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qbuttongroup.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcalendarwidget.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcheckbox.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcommandlinkbutton.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdatetimeedit.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdial.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialogbuttonbox.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfocusframe.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfontcombobox.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qframe.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgroupbox.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qkeysequenceedit.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlcdnumber.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdiarea.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmdisubwindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressbar.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qradiobutton.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qrubberband.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollarea.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollbar.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsizegrip.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qspinbox.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplashscreen.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedwidget.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstatusbar.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabbar.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtabwidget.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextbrowser.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbar.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbox.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtwidgetsversion.h \
		../../../Qt/5.4/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QPrintDialog \
		../../../Qt/5.4/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintdialog.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../../Qt/5.4/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QPrintPreviewDialog \
		../../../Qt/5.4/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintpreviewdialog.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QCheckBox \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QCloseEvent \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QFontMetrics \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QAbstractItemDelegate \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QContextMenuEvent \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSplitter
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

Vegetable.o: Vegetable.cpp ../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		returnto.h \
		Return.h \
		History.h \
		Remaining.h \
		Vegetable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Vegetable.o Vegetable.cpp

Inventory.o: Inventory.cpp ../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		Return.h \
		returnto.h \
		History.h \
		Remaining.h \
		Vegetable.h \
		Inventory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Inventory.o Inventory.cpp

History.o: History.cpp ../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		History.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o History.o History.cpp

Remaining.o: Remaining.cpp Remaining.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Remaining.o Remaining.cpp

Return.o: Return.cpp ../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qDebug \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		Return.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Return.o Return.cpp

returnto.o: returnto.cpp ../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qDebug \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		returnto.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o returnto.o returnto.cpp

translator.o: translator.cpp translator.h \
		IConst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o translator.o translator.cpp

imenubar.o: imenubar.cpp imenubar.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		translator.h \
		IConst.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		dialog.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		Inventory.h \
		returnto.h \
		Return.h \
		History.h \
		Remaining.h \
		Vegetable.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListWidgetItem \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../../Qt/5.4/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QPrinter \
		../../../Qt/5.4/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprinter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imenubar.o imenubar.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_imenubar.o: moc_imenubar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imenubar.o moc_imenubar.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

